### ISSUE TITLE
Postgres connection pool is exhausted for some reason

### ISSUE THREAD

**Issue by seano-vs** [Five-Borough-Fedi-Project/masto.nyc-docean#10]
Even after [putting pgbouncer in between the app stack and the database](https://github.com/Five-Borough-Fedi-Project/masto.nyc-docean/blob/main/databases.tf#L27-L34), the web server and sidekiq are still complaining about the connection pool being empty:

```
WARN: ActiveRecord::ConnectionTimeoutError: 
could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); 
all pooled connections were in use
...
WARN: /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/connection_pool/queue.rb:126:in `block in wait_poll'
...
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/connection_pool/queue.rb:115:in `loop'
...
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8.4/lib/active_record/connection_adapters/abstract/connection_pool/queue.rb:115:in `wait_poll'

```

Even though the error seems self explanatory, there aren't a lot of details online [except for this](https://blog.thms.uk/2023/07/tweaking-postgres-mastodon?utm_source=mastodon). I increased the `DB_POOL` env to 10 and the issue still persists.

It's especially frustrating because our connection pool is configured to use 85 connections, and I've never seen it use more than, say, 10 in the "current connections" UI of DOcean. It just now gave that error, and there are currently 6 connections.

This is going to require some more debugging.

**Comment by seano-vs** [comment]
Fixed, with evidence from the Sidekiq dead set.

The cause was `DB_POOL=10` set globally in `mastodon-env-secret` while every Sidekiq deployment ran `-c 25`. Twenty-five threads shared ten connections, so fifteen of them queued and timed out after five seconds. That also explains the part that was most confusing here — the pool looked idle from DigitalOcean's side. It was. The exhausted pool was ActiveRecord's, inside each Ruby process, not pgbouncer's and not Postgres's. Raising `DB_POOL` to 10 did not help because the number that mattered was 25.

The three Sidekiq deployments now override `DB_POOL` to 25 to match `-c 25`.

Counting `ActiveRecord::ConnectionTimeoutError` in the dead set by the day it failed:

| day | dead jobs | of those, connection timeouts |
|---|---|---|
| 2026-08-27 | 416 | **370** |
| 2026-08-28 | 77 | 0 |
| 2026-08-29 | 32 | 0 |
| 2026-08-30 | 28 | 0 |
| 2026-08-31 | 10 | 0 |
| 2026-09-01 | 24 | 0 |
| 2026-09-02 | 44 | 0 |
| 2026-09-03 | 23 | 0 |
| 2026-09-04 | 25 | 0 |
| 2026-09-05 | 18 | 0 |
| 2026-09-06 | 32 | 0 |

869 in the dead set overall, and none since 2026-08-27. The 10 to 45 a day since are `HTTP::TimeoutError`, `HTTP::ConnectionError` and `OpenSSL::SSL::SSLError` against remote instances, which is ordinary federation.

Related, from the same review: `mastodon-sidekiq-sched` was also running `-c 25` with `DB_POOL=25` to service the scheduler queue alone, which holds 25 connections for periodic jobs that do not need them. #78 drops it to 5. That takes the theoretical maximum from 115 to 95 against a pgbouncer pool of 85.
